import * as admin from 'firebase-admin';
import path from 'path';
import config from '../../../config';
import { logger } from '../../../shared/logger';

// Initialize Firebase Admin
let isFirebaseInitialized = false;

const initializeFirebase = () => {
    try {
        const serviceAccountPath = path.join(process.cwd(), 'serviceAccountKey.json');

        if (admin.apps.length === 0) {
            admin.initializeApp({
                credential: admin.credential.cert(serviceAccountPath),
            });
            logger.info('Firebase Admin initialized successfully');
        }

        isFirebaseInitialized = true;
    } catch (error: any) {
        logger.error('Firebase Admin initialization failed:', error);
    }
};

const sendPushNotification = async (
    fcmToken: string,
    title: string,
    body: string,
    data?: Record<string, any>
) => {
    if (!fcmToken || typeof fcmToken !== 'string' || fcmToken.trim() === '') {
        console.error('❌ [PushNotification] FAILED: FCM token is empty or missing. Cannot send push notification. Title:', title);
        logger.error('Push notification failed: Empty FCM token');
        return;
    }

    if (!isFirebaseInitialized) {
        initializeFirebase();
    }

    if (!isFirebaseInitialized) {
        console.error('❌ [PushNotification] FAILED: Firebase Admin is not initialized. Check serviceAccountKey.json');
        logger.warn('Push notification skipped: Firebase not initialized');
        return;
    }

    // Convert all data values to strings (FCM requirement)
    const stringifiedData: Record<string, string> = {};
    if (data) {
        Object.entries(data).forEach(([key, value]) => {
            stringifiedData[key] = value?.toString() || '';
        });
    }

    const message: admin.messaging.Message = {
        notification: {
            title,
            body,
        },
        data: stringifiedData,
        token: fcmToken,
    };

    try {
        const response = await admin.messaging().send(message);
        console.log(`✅ [PushNotification] Push notification sent successfully! Message ID: ${response}`);
        logger.info(`Push notification sent successfully: ${response}`);
        return response;
    } catch (error: any) {
        let reason = 'Unknown Firebase error';
        if (error.code === 'messaging/registration-token-not-registered') {
            reason = 'Token is NOT registered / expired. The mobile app may have been uninstalled, reinstalled, or the FCM token changed and needs to be updated in DB.';
        } else if (error.code === 'messaging/invalid-registration-token') {
            reason = 'The registration token format is invalid.';
        } else if (error.code === 'messaging/mismatched-credential') {
            reason = 'Firebase project mismatch. The token was generated by a different Firebase project than the serviceAccountKey.json.';
        } else if (error.code === 'messaging/invalid-argument') {
            reason = 'Invalid payload arguments or malformed token string.';
        } else if (error.code === 'messaging/authentication-error') {
            reason = 'Firebase Admin authentication failed. Verify serviceAccountKey.json.';
        } else if (error.code === 'messaging/server-unavailable') {
            reason = 'FCM server is temporarily unavailable.';
        }

        console.error('==================== PUSH NOTIFICATION FAILED ====================');
        console.error(`❌ Notification Title : "${title}"`);
        console.error(`❌ Target FCM Token   : ${fcmToken}`);
        console.error(`❌ Error Code         : ${error.code || 'UNKNOWN'}`);
        console.error(`❌ Error Message      : ${error.message}`);
        console.error(`❌ Why it failed      : ${reason}`);
        if (error.errorInfo) {
            console.error(`❌ Error Details      :`, JSON.stringify(error.errorInfo, null, 2));
        }
        console.error('==================================================================');

        logger.error(`Error sending push notification: ${error.message} (${error.code})`);
    }
};

export const PushNotificationService = {
    sendPushNotification,
};
